version: '3.7'

services:
  surging.sample.auth:
    environment:
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      Environment: ${ENVIRONMENT:-Development}
      ForceDisplayStackTrace: ${FORCED_DISPLAY_STACKTRACE:-false}
      DbType: ${AUTH_DB_TYPE:-Mysql}
      ConnectionString: ${AUTH_DB_CONN}
      SwaggerTitle: "surging.sample.auth"
      SwaggerDes: "身份认证与授权服务组件API文档"
      SupportName: "liuhongliang"
      SupportEmail: "liuhongliang@jingshonline.com"
      EnableAuthorization: ${ENABLE_AUTHORIZATION:-false}
    ports:
      - "18081:8080"

  surging.sample.user:
    environment:
      Register_Conn: ${REGISTER_CONN:-consul:8500}
      Register_SessionTimeout: ${REGISTER_SESSION_TIMEOUT:-50}
      UseEngineParts: ${NORMAL_SERVER_ENGINE}
      EventBusConnection: ${RABBITMQ_CONNECTION:-hero.rabbitmq}
      EventBusUserName:  ${RABBITMQ_USERNAME:-rabbitmq}
      EventBusPassword:  ${RABBITMQ_PASSWORD:-rabbitmq}
      EventBusPort: ${RABBITMQ_PORT:-5672}
      ForceDisplayStackTrace: ${FORCED_DISPLAY_STACKTRACE:-false}
      DbType: ${USERDATA_DB_TYPE:-Mysql}
      ConnectionString: ${USERDATA_DB_CONN}
      SwaggerTitle: "surging.sample.user"
      SwaggerDes: "用户组件相关API文档"
      SupportName: "liuhongliang"
      SupportEmail: "liuhongliang@jingshonline.com"
      EnableAuthorization: ${ENABLE_AUTHORIZATION:-false}
    ports:
      - "18082:8080" 